### ISSUE TITLE
deploy KeeperKeeper

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/badger-infra#3]
chainlink's keeper jobs ("upkeeps") need to be registered through their onchain registry, and funded through that same registry with $link. right now this is done through their ui using gnosis' walletconnect app.

a single keeper's keeper contract, funded with $link (or ether and onchain swap) could maintain all our upkeeps. it would serve as the actor of the following tasks:
- register an upkeep (admin only)
- cancel an upkeep and withdraw remaining $link (admin only)
- top up any upkeeps that reach low funds (this task itself also being an upkeep, ie the keeperkeeper would register itself as an upkeep)

this would then reduce all tasks to a single manual task: to make sure the keeperkeeper has enough ether/$link.

**Comment by gosuto-inzasheru** [comment]
basically replacing current monitoring and interaction with https://keepers.chain.link/mainnet (connected to using techops) by a smart contract

**Comment by dapp-whisperer** [comment]
can you expand on the current status?
- did chainlink release the feature or it is it known to be on the roadmap?

> basically replacing current monitoring and interaction with https://keepers.chain.link/mainnet (connected to using techops) by a smart contract

how does the current monitoring / interaction system work?

**Comment by gosuto-inzasheru** [comment]
> how does the current monitoring / interaction system work?

currently the 'admin' of the keeper jobs is techops. this means we have to write scripts to register&fund ($link) and turn off keeper jobs&reclaim funds. monitoring has to be done fully manually, ie is there enough $link present, is the job still current etc.

with the release of chainlink's new registry v1.2 (https://docs.chain.link/docs/chainlink-keepers/keepers-release-notes/#2022-08-04---v12-release), it is now possible to do perform all these managing tasks directly from a smart contract:
> Programmatic control: With automatic approval, you can now dynamically create, manage, and fund upkeeps from within your dApps and even have an upkeep fund itself. Learn more [here](https://docs.chain.link/docs/chainlink-keepers/register-upkeep/#register-an-upkeep-using-your-own-deployed-contract).

**Comment by gosuto-inzasheru** [comment]
replaced by UpkeepManager contract in https://github.com/Badger-Finance/badger-avatars/
